### ISSUE TITLE
TypeError: Cannot convert undefined or null to object 

### ISSUE THREAD

**Issue by AlexSun98** [ACloudGuru/serverless-plugin-aws-alerts#108]
Below errorr occurred when I ran serveless cmd, any clues please? thank you.
./node_modules/.bin/serverless package --package ./build

nodejs version - v12
serverless version - 1.50.2
serverless-plugin-aws-alerts version - v1.4

**Configuration:**
alerts:
  dashboards: true
  topics:
    alarm:  
      topic: ${self:service}-${self:custom.stage}-alarm
      notifications:
        - protocol: ${self:custom.${self:custom.stage}-alarm-notification-protocol}
          endpoint: ${self:custom.${self:custom.stage}-alarm-notification-endpoint}
    events:
  definitions:
    CustomAlarm:
      description: Health Monitor'
      namespace: "AWS/Lambda"
      metric: Exceptions
      threshold: 3
      statistic: Sum
      period: 900
      evaluationPeriods: 1
      comparisonOperator: GreaterThanOrEqualToThreshold
      pattern: '{$.state = "Error*"}'
    CustomAPIAlarm:
      description: 'API Health Monitor'
      namespace: "AWS/Lambda"
      metric: APICriticalExceptions
      threshold: 3
      statistic: Sum
      period: 900
      evaluationPeriods: 1
      comparisonOperator: GreaterThanOrEqualToThreshold
      pattern: ''
  alarms:
    - CustomAPIAlarm
    - CustomAlarm

**The error detail can be found as following:** 
`**TypeError: Cannot convert undefined or null to object** 
      at Function.keys (<anonymous>) 
      at Object.keys.forEach (/codebuild/output/src932548716/src/node_modules/serverless-plugin-aws-alerts/src/index.js:216:14) 
      at Array.forEach (<anonymous>) 
      at AlertsPlugin.compileAlertTopics (/codebuild/output/src932548716/src/node_modules/serverless-plugin-aws-alerts/src/index.js:212:34) 
      at AlertsPlugin.compile (/codebuild/output/src932548716/src/node_modules/serverless-plugin-aws-alerts/src/index.js:356:30) 
      at BbPromise.reduce (/codebuild/output/src932548716/src/node_modules/serverless/lib/classes/PluginManager.js:505:55) 
      at tryCatcher (/codebuild/output/src932548716/src/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23) 
      at Object.gotValue (/codebuild/output/src932548716/src/node_modules/serverless/node_modules/bluebird/js/release/reduce.js:157:18) 
      at Object.gotAccum (/codebuild/output/src932548716/src/node_modules/serverless/node_modules/bluebird/js/release/reduce.js:144:25) 
      at Object.tryCatcher (/codebuild/output/src932548716/src/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23) 
      at Promise._settlePromiseFromHandler (/codebuild/output/src932548716/src/node_modules/serverless/node_modules/bluebird/js/release/promise.js:517:31) 
      at Promise._settlePromise (/codebuild/output/src932548716/src/node_modules/serverless/node_modules/bluebird/js/release/promise.js:574:18) 
      at Promise._settlePromise0 (/codebuild/output/src932548716/src/node_modules/serverless/node_modules/bluebird/js/release/promise.js:619:10) 
      at Promise._settlePromises (/codebuild/output/src932548716/src/node_modules/serverless/node_modules/bluebird/js/release/promise.js:699:18) 
      at _drainQueueStep (/codebuild/output/src932548716/src/node_modules/serverless/node_modules/bluebird/js/release/async.js:138:12) 
      at _drainQueue (/codebuild/output/src932548716/src/node_modules/serverless/node_modules/bluebird/js/release/async.js:131:9) 
      at Async._drainQueues (/codebuild/output/src932548716/src/node_modules/serverless/node_modules/bluebird/js/release/async.js:147:5) 
      at Immediate.Async.drainQueues (/codebuild/output/src932548716/src/node_modules/serverless/node_modules/bluebird/js/release/async.js:17:14) 
      at runCallback (timers.js:810:20) 
      at tryOnImmediate (timers.js:768:5) 
      at processImmediate [as _immediateCallback] (timers.js:745:5) `

**Comment by AlexSun98** [comment]
Did anyone experience the same issue before? Wondering if the problem related to library's dependencies' version?

**Comment by bulkan** [comment]
Hi @AlexSun98 

The serverless version you're using isn't supported by this plugin just yet.
