### ISSUE TITLE
serverless.configSchemaHandler.defineFunctionProperties is not a function

### ISSUE THREAD

**Issue by R11baka** [ACloudGuru/serverless-plugin-aws-alerts#173]
# Can't deploy lambda on aws

## 
When run sls deploy I got an error  with message
`TypeError: serverless.configSchemaHandler.defineFunctionProperties is not a function
at new AlertsPlugin (/builds/lambda/api-partner-management/node_modules/serverless-plugin-aws-alerts/src/index.js:15:36)`

## Additional Data

* ***Serverless Framework Version***:1.83.3
* ***Stack Trace***: ` Type Error ---------------------------------------------
 
  TypeError: serverless.configSchemaHandler.defineFunctionProperties is not a function
      at new AlertsPlugin (/builds/lambda/api-partner-management/node_modules/serverless-plugin-aws-alerts/src/index.js:15:36)
      at PluginManager.addPlugin (/home/ciq/.npm-packages/lib/node_modules/serverless/lib/classes/PluginManager.js:94:28)
      at /home/ciq/.npm-packages/lib/node_modules/serverless/lib/classes/PluginManager.js:129:31
      at Array.forEach (<anonymous>)
      at PluginManager.loadAllPlugins (/home/ciq/.npm-packages/lib/node_modules/serverless/lib/classes/PluginManager.js:129:8)
      at /home/ciq/.npm-packages/lib/node_modules/serverless/lib/Serverless.js:88:39
      at tryCatcher (/home/ciq/.npm-packages/lib/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/home/ciq/.npm-packages/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/home/ciq/.npm-packages/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (/home/ciq/.npm-packages/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/home/ciq/.npm-packages/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:729:18)
      at Promise._fulfill (/home/ciq/.npm-packages/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:673:18)
      at Promise._settlePromise (/home/ciq/.npm-packages/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:617:21)
      at Promise._settlePromise0 (/home/ciq/.npm-packages/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/home/ciq/.npm-packages/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:729:18)
      at Promise._fulfill (/home/ciq/.npm-packages/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:673:18)
      at Promise._resolveCallback (/home/ciq/.npm-packages/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:466:57)
      at Promise._settlePromiseFromHandler (/home/ciq/.npm-packages/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:559:17)
      at Promise._settlePromise (/home/ciq/.npm-packages/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (/home/ciq/.npm-packages/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/home/ciq/.npm-packages/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:729:18)
      at Promise._fulfill (/home/ciq/.npm-packages/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:673:18)
      at PromiseArray._resolve (/home/ciq/.npm-packages/lib/node_modules/serverless/node_modules/bluebird/js/release/promise_array.js:127:19)
      at PromiseArray._promiseFulfilled (/home/ciq/.npm-packages/lib/node_modules/serverless/node_modules/bluebird/js/release/promise_array.js:145:14)
      at Promise._settlePromise (/home/ciq/.npm-packages/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:609:26)
      at Promise._settlePromise0 (/home/ciq/.npm-packages/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/home/ciq/.npm-packages/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:729:18)
      at Promise._fulfill (/home/ciq/.npm-packages/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:673:18)
      at Promise._resolveCallback (/home/ciq/.npm-packages/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:466:57)
      at Promise._settlePromiseFromHandler (/home/ciq/.npm-packages/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:559:17)
      at Promise._settlePromise (/home/ciq/.npm-packages/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (/home/ciq/.npm-packages/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/home/ciq/.npm-packages/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:729:18)
      at Promise._fulfill (/home/ciq/.npm-packages/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:673:18)
      at PropertiesPromiseArray.PromiseArray._resolve (/home/ciq/.npm-packages/lib/node_modules/serverless/node_modules/bluebird/js/release/promise_array.js:127:19)
      at PropertiesPromiseArray._promiseFulfilled (/home/ciq/.npm-packages/lib/node_modules/serverless/node_modules/bluebird/js/release/props.js:78:14)
      at Promise._settlePromise (/home/ciq/.npm-packages/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:609:26)
      at Promise._settlePromise0 (/home/ciq/.npm-packages/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/home/ciq/.npm-packages/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:729:18)
      at _drainQueueStep (/home/ciq/.npm-packages/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:93:12)
      at _drainQueue (/home/ciq/.npm-packages/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (/home/ciq/.npm-packages/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (/home/ciq/.npm-packages/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:15:14)
      at processImmediate (internal/timers.js:461:21)
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              12.22.1
     Framework Version:         1.83.3
     Plugin Version:            3.8.4
     SDK Version:               2.3.2
     Components Version:        2.34.9`
* ***Provider Error messages***: serverless.configSchemaHandler.defineFunctionProperties is not a function

**Comment by Filmhooligan** [comment]
I'm also having this issue, reverting to the last plugin version 1.6.1 allowed serverless deploys to go through again.
https://github.com/ACloudGuru/serverless-plugin-aws-alerts/commit/9c6421815eb416bd150c4cca8b4a8e03b269766c#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519
 @R11baka
