### ISSUE TITLE
TypeError: Cannot read property 'alarm' of undefined

### ISSUE THREAD

**Issue by saintzyo** [ACloudGuru/serverless-plugin-aws-alerts#174]
# This is a Bug Report

## Description

When run sls deploy I got an error with message: TypeError: Cannot read property 'alarm' of undefined
aws-alerts plugin version 1.6.1

## Additional Data

* ***Serverless Framework Version***: 1.83.3
* ***Stack Trace***: 
Type Error ---------------------------------------------
 
  TypeError: Cannot read property 'alarm' of undefined
      at /builds/discovery/es-api/node_modules/serverless-plugin-aws-alerts/src/index.js:99:93
      at Array.map (<anonymous>)
      at AlertsPlugin.getAlarmCloudFormation (/builds/discovery/es-api/node_modules/serverless-plugin-aws-alerts/src/index.js:99:31)
      at /builds/discovery/es-api/node_modules/serverless-plugin-aws-alerts/src/index.js:281:25
      at Array.reduce (<anonymous>)
      at /builds/discovery/es-api/node_modules/serverless-plugin-aws-alerts/src/index.js:279:38
      at Array.forEach (<anonymous>)
      at AlertsPlugin.compileAlarms (/builds/discovery/es-api/node_modules/serverless-plugin-aws-alerts/src/index.js:271:47)
      at AlertsPlugin.compile (/builds/discovery/es-api/node_modules/serverless-plugin-aws-alerts/src/index.js:358:10)
      at /home/ciq/.npm-packages/lib/node_modules/serverless/lib/classes/PluginManager.js:498:55
      at tryCatcher (/home/ciq/.npm-packages/lib/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
      at Object.gotValue (/home/ciq/.npm-packages/lib/node_modules/serverless/node_modules/bluebird/js/release/reduce.js:168:18)
      at Object.gotAccum (/home/ciq/.npm-packages/lib/node_modules/serverless/node_modules/bluebird/js/release/reduce.js:155:25)
      at Object.tryCatcher (/home/ciq/.npm-packages/lib/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/home/ciq/.npm-packages/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/home/ciq/.npm-packages/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (/home/ciq/.npm-packages/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/home/ciq/.npm-packages/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:729:18)
      at _drainQueueStep (/home/ciq/.npm-packages/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:93:12)
      at _drainQueue (/home/ciq/.npm-packages/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (/home/ciq/.npm-packages/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (/home/ciq/.npm-packages/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:15:14)
      at processImmediate (internal/timers.js:461:21)
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
* ***Provider Error messages***: TypeError: Cannot read property 'alarm' of undefined

**Comment by saintzyo** [comment]
So, the root of the issue is:
we are using globally installed sls and plugins and their versions are correct (1.83.3 and 1.6.1) also we have enableLocalInstallationFallback: false parameter and it works correctly, sls is used from global node_modules. But, it takes the alarm plugin from the service node_modules and there it has old version 1.6.1.
Does anybody know how to tell serverless to use globally installed plugins?
Thanks!

**Comment by asethi19** [comment]
Facing the same issue.
